Dodati integracioni testovi za schedMedExam, Izmenjen response za search rutu
RAF-SI-2022/Bolnica-2-Backend pull request #105
Opened 2023-04-01 21:59 UTC by AlekZivkovic

```
/sched-med-exam/search
``` 
sada vraca u svom sadrzaju takodje info o pacijentu

test coverage oko 90%

2023-04-01 22:09 UTC, AlekZivkovic commented on patient-service/src/test/java/com/raf/si/patientservice/integration/UtilsHelper.java
> +        String token="eyJhbGciOiJIUzUxMiJ9.eyJmaXJzdE5hbWUiOiJNZWRpY2luc2thIiwibGFzdE5hbWUiOiJTZXN0cmEiLCJ0aXRsZSI6IkRpcGwuIGZhcm0uIiwicHJvZmVzc2lvbiI6Ik1lZC4gc2VzdHJhIiwicGJvIjoiNGU1OTExYzgtY2U3YS0x
Nisam se setio nekog lepseg nacina, valda je ovo isto oke

2023-04-01 22:12 UTC, AlekZivkovic commented on patient-service/src/main/java/com/raf/si/patientservice/dto/response/SchedMedExamExtendedResponse.java
> +public class SchedMedExamExtendedResponse extends SchedMedExamResponse{
Kako je trazeno da se vrati i info o pacijentu odlucio sam da ne bi duplirao kod samo da nadodam u posebnu klasu. Jer nece uvek trebati da se prikazuje info o pacijentu, npr. tokom pravljenja.

2023-04-02 10:03 UTC, filip-filipovic commented on patient-service/src/test/java/com/raf/si/patientservice/integration/UtilsHelper.java
> +        String token="eyJhbGciOiJIUzUxMiJ9.eyJmaXJzdE5hbWUiOiJNZWRpY2luc2thIiwibGFzdE5hbWUiOiJTZXN0cmEiLCJ0aXRsZSI6IkRpcGwuIGZhcm0uIiwicHJvZmVzc2lvbiI6Ik1lZC4gc2VzdHJhIiwicGJvIjoiNGU1OTExYzgtY2U3YS0x
Nije, jer ce u nekom trenutku ovaj token da istekne, pa testovi nece prolaziti

2023-04-02 10:05 UTC, filip-filipovic requested changes
Popravi token za medicinsku sestru

2023-04-02 10:53 UTC, merged

2023-04-02 13:33 UTC, mceculovic commented on patient-service/src/main/java/com/raf/si/patientservice/service/impl/SchedMedExaminationServiceImpl.java
> +                    return schedMedExamResponse;
Ovde je problem sto za svaki red u listi mi pozivamo bazu, ne znam zasto u modelu za zakazivanje nemamo pacijenta kao many to one vec imamo samo lbp, time bi resili ovo a i vracali bi svuda pacijenta