Dodati testovi
RAF-SI-2022/Bolnica-2-Backend pull request #178
Opened 2023-05-06 17:44 UTC by dragicevicb

2023-05-14 17:52 UTC, mceculovic requested changes

2023-05-14 17:52 UTC, mceculovic commented on laboratory-service/src/main/java/com/raf/si/laboratoryservice/mapper/OrderMapper.java
> +
Da li nam je potreban ovaj kod?

2023-05-14 17:52 UTC, mceculovic commented on laboratory-service/src/main/java/com/raf/si/laboratoryservice/service/impl/WorkOrderServiceImplementation.java
> +        System.out.println(referral.toString());
Ako zelis da ispises nesto relevantno za debug-ovanje, mozes koristiti logger, u slucaju da si samo proveravao nesto, mozes obrisati ovo

2023-05-14 17:52 UTC, mceculovic commented on laboratory-service/src/main/resources/application-prod.yaml
> +    url: "jdbc:postgresql://localhost:5434/postgresDB"
Ne znam zasto si ovo menjao, postoji application-dev.yaml koji mozes da startujes, svakako ovo treba vratiti

2023-05-14 17:52 UTC, mceculovic commented on user-service/src/main/java/com/raf/si/userservice/bootstrap/BootstrapData.java
> +public class  BootstrapData implements CommandLineRunner {
Mozes da formatiras fajl kad nesto promenis cisto zbog ovakvih stvari

2023-05-15 11:54 UTC, dragicevicb commented
Dodao sam promene koje si trazio.

2023-05-15 17:15 UTC, mceculovic approved these changes

2023-05-15 17:16 UTC, merged