Vaccination-Model: Dodadat SchedVacc model
RAF-SI-2022/Bolnica-2-Backend pull request #221
Opened 2023-06-15 15:33 UTC by AlekZivkovic

Takodje su izmenjene dodatno neke klase da reflect na SchedVacc

2023-06-15 15:35 UTC, AlekZivkovic commented
Radio sam ugledajuci se na SchedTest model

2023-06-18 22:26 UTC, AlekZivkovic commented on patient-service/src/main/java/com/raf/si/patientservice/model/ScheduledVaccinationCovid.java
> +    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
Ae ako mozes samo isprati dal samo lepo povezao klase. Mislim da jesam al ples proveri

2023-06-23 17:41 UTC, mceculovic requested changes

2023-06-23 17:41 UTC, mceculovic commented on patient-service/src/main/java/com/raf/si/patientservice/model/VaccinationCovid.java
> +    @JoinColumn(name = "vaccine_id", nullable = false)
Dodaj samo referenced column

2023-06-23 17:41 UTC, mceculovic commented on patient-service/src/main/java/com/raf/si/patientservice/model/VaccinationCovid.java
> +    @JoinColumn(name = "health_record_id", nullable = false)
isto dodaj referencedColumnName= "id"

2023-06-24 12:55 UTC, AlekZivkovic commented on patient-service/src/main/java/com/raf/si/patientservice/model/VaccinationCovid.java
> +    @JoinColumn(name = "vaccine_id", nullable = false)
Upravo dodao.

2023-06-24 12:56 UTC, AlekZivkovic commented on patient-service/src/main/java/com/raf/si/patientservice/model/VaccinationCovid.java
> +    @JoinColumn(name = "health_record_id", nullable = false)
Upravo dadao

2023-06-24 14:41 UTC, merged