Dodat REST API za azuriranje statusa pregleda
RAF-SI-2022/Bolnica-2-Backend pull request #67
Opened 2023-03-23 21:00 UTC by AlekZivkovic

Dodatno izbrisan whitespace u modelu

2023-03-23 21:49 UTC, filip-filipovic commented on patient-service/src/main/java/com/raf/si/patientservice/mapper/SchedMedExamMapper.java
> +            case OTKAZANO:
Zasto ne moze da se otkaze pregled?

2023-03-23 21:52 UTC, filip-filipovic requested changes
Deluje mi da za update treba dozvoliti da se status pregleda postavi na otkazano. Takodje, mozda bi bilo okej i da moze da se postavi na zakazan, mada nisam siguran koliko bi to bilo korisno

2023-03-23 23:03 UTC, AlekZivkovic commented on patient-service/src/main/java/com/raf/si/patientservice/mapper/SchedMedExamMapper.java
> +            case OTKAZANO:
Tako je pisalo u spec nije ni meni bilo najjasnije sto su bas tako htelo, pogedaj 3.2.1.3.2.2., al et.
Uglvm Otkazano bi trebalo da bude moguce samo kroz 3.2.1.3.2.3. Ažuriranje podatka Status o prispeću pacijenta.

2023-03-23 23:17 UTC, AlekZivkovic commented
Na zakazn se stavlja po defaultu kad se napravi zakazani pregled. Donekle mislim da je ne bi trebalo omoguci pri izmeni da se ponovo stavi jer moze samo da se kreira novi. 
Sto ne bi trebalo da se onemoguci npr :
Prvi slucaj:
Pacijent otkazao pregled, pregled prebacen na OTKAZANO. Posle nekoliko sati korisnik se ipak odluci da hoce pregled. Ali medjutim taj termin je popunjen, neko drugi zakazao,  sto onda dovodi do toga da uopste nije moguce izmenti termin neg mora da se zakazuje novi termin za pregled aka kreira novi zakazani pregled.

Drugi slucaj:
Recimo da pacijent isto otkazao pregled i da je posle nekog vremena odlucio da ipak zeli nasu uslugu tj pregled. Medjutim lekar moguce da je u to vreme vise nije slobodan, tj myb uzeo odmor?,  pri cemu je samo bolje da ponovo zakaze nov pregled.

2023-03-24 00:03 UTC, filip-filipovic commented on patient-service/src/main/java/com/raf/si/patientservice/mapper/SchedMedExamMapper.java
> +            case OTKAZANO:
Jeste, moja greska. Izgleda da su tako trazili, iako mi nema bas previse smisla

2023-03-24 00:04 UTC, filip-filipovic commented
Ima smisla. Onda bi mozda za tu situaciju trebao takodje da se baci exception?

2023-03-24 09:10 UTC, AlekZivkovic commented on patient-service/src/main/java/com/raf/si/patientservice/mapper/SchedMedExamMapper.java
> +            case OTKAZANO:
Ma da i meni je kinda bzvz

2023-03-24 09:19 UTC, AlekZivkovic commented
Hmm da za tak nest, ak pustimo da moze da se azurira, bi morali da cover takvu situaciju, al onda bi i takodje morali da dodatno menmjamo neke stvari nrp koja je sestra zakazala ili idk mozda mu se prosli izabrani lekar nesvidja sto bi znacilo da menja sve again.

Donekle kak sam ja razumeo OTKAZANO state je vise kao _soft delete_, sto nez dal bi trebali da menjamo "izbrisan" pregled.
Uglvanom kak je sad se proverava  se dal je uopste moguce zakazati pregled, ima comment u servisu gde se to radi, tho ak zelis da omogucim jos nest da se auzira dm me danas.

2023-03-24 09:47 UTC, filip-filipovic commented
Za OTKAZANO se slazem da ostane kako je i sad, pitao sam za ZAKAZANO. Ako ne moze da se promeni na zakazano, mislim da je bolje da se baci neki exception umesto da se nista ne odradi na backendu, a da frontend misli da je sve okej

2023-03-24 10:56 UTC, merged